export const RecommandCarousel = [
  {
    contentId: 7767,
    firstImageUrl: "https://gocamping.or.kr/upload/camp/7767/thumb/thumb_720_6897zhFRTiMXgMH1DUbtVRcI.jpg",
    doNm: "충청남도",
    sigunguNm: "보령시",
    facltNm: "대천용두야영장",
    lineIntro: "기막힌 경관의 MBC ‘나 혼자 산다’ 촬영지",
  },
  {
    contentId: 8014,
    firstImageUrl: "https://gocamping.or.kr/upload/camp/8014/thumb/thumb_720_4703Qm7QalwokiTMJMJJxt8m.jpg",
    doNm: "인천시",
    sigunguNm: "서구",
    facltNm: "수도권매립지 캠핑장",
    lineIntro: "",
  },
  {
    contentId: 2672,
    firstImageUrl: "https://gocamping.or.kr/upload/camp/2672/thumb/thumb_720_8622MUgbQjvlvxxPtpZckjRE.jpg",
    doNm: "강원도",
    sigunguNm: "삼척시",
    facltNm: "장호비치캠핑장",
    lineIntro: "동해안에서 가장 아름답다는 장호해변 언덕에 위치한 휴양 캠핑 시설",
  },
  {
    contentId: 6787,
    firstImageUrl: "https://gocamping.or.kr/upload/camp/6787/thumb/thumb_720_4382980LaD7pgCXsyNvl4UkP.jpg",
    doNm: "대전시",
    sigunguNm: "대덕구",
    facltNm: "로하스 가족공원 캠핑장",
    lineIntro: "대청댐앞에 위치한 리조트형 캠핑장",
  },
  {
    contentId: 6975,
    firstImageUrl: "https://gocamping.or.kr/upload/camp/6975/thumb/thumb_720_8864VHhvenUMGtZByAoSmY82.jpg",
    doNm: "강원도",
    sigunguNm: "정선군",
    facltNm: "동강전망휴양림오토캠핑장",
    lineIntro: "운해와 야경이 일품인 휴양림속 야영장",
  },
  {
    contentId: 3120,
    firstImageUrl: "https://gocamping.or.kr/upload/camp/3120/thumb/thumb_720_2230dMoalowTL1SnrYjBhF59.jpg",
    doNm: "경기도",
    sigunguNm: "고양시",
    facltNm: "킨텍스캠핑장 ",
    lineIntro: "서울 근교 도심 속에서 즐기는 캠핑장",
  },
  {
    contentId: 1447,
    firstImageUrl: "https://gocamping.or.kr/upload/camp/1447/thumb/thumb_720_7831YRImoCw9egHpHvfThEbZ.jpg",
    doNm: "경상남도",
    sigunguNm: "사천시",
    facltNm: "비토섬 신우리조트 모던글램핑",
    lineIntro: "토끼와 거북이가 살았던 별주부 전설의 비토섬에서 캠핑을",
  },
  {
    contentId: 2038,
    firstImageUrl: "https://gocamping.or.kr/upload/camp/2038/thumb/thumb_720_79872wN24Px6afS0mvrhy7AZ.jpg",
    doNm: "경기도",
    sigunguNm: "포천시",
    facltNm: "가래골농원 캠핑장2",
    lineIntro: "탁 트인 시원한 전망에서 즐기는 힐링 캠프 ",
  },
  {
    contentId: 2538,
    firstImageUrl: "https://gocamping.or.kr/upload/camp/2538/thumb/thumb_720_6392TqzWLZaa7aO26szEuJID.jpg",
    doNm: "강원도",
    sigunguNm: "춘천시",
    facltNm: "엘리시안 강촌 캠핑파크",
    lineIntro: "엘리시안 강촌리조트에 마련한 캠핑장",
  },
  {
    contentId: 3105,
    firstImageUrl: "https://gocamping.or.kr/upload/camp/3105/thumb/thumb_720_88096ybOGjPI20shqdQSUPMa.jpg",
    doNm: "강원도",
    sigunguNm: "홍천군",
    facltNm: "석산계곡 코코비발디 글램핑  카라반 오토캠핑장 ",
    lineIntro: "산과 계곡으로 둘러쌓인 글램핑, 카라반,  오토캠핑장이 준비되어 있습니다 ",
  },
  {
    contentId: 8029,
    firstImageUrl: "https://gocamping.or.kr/upload/camp/8029/thumb/thumb_720_06451bwXakERFfx0EdjH0sCu.jpg",
    doNm: "인천시",
    sigunguNm: "강화군",
    facltNm: "강화카라반해변",
    lineIntro: "강화도에서 느껴 보는 스페인의 이국적인 감성",
  },
  {
    contentId: 7635,
    firstImageUrl: "https://gocamping.or.kr/upload/camp/7635/thumb/thumb_720_3686hrSi0AhEPk2vQMgJ20ao.jpg",
    doNm: "경기도",
    sigunguNm: "포천시",
    facltNm: "산중호걸 글램핑",
    lineIntro: "약사동계곡에 위치한 청정지역 카라반&글램핑",
  },
];
