import { DONAME } from "../../types/administrativeDivision";
import { AdvancedSearchFormInterface } from "../../types/searchBoxForm";

export const AdvancedSearchParams: AdvancedSearchFormInterface = {
  region: {
    id: "category_region",
    title: "지역별",
    content: [
      { id: "category_region_1", name: DONAME.Seoul },
      { id: "category_region_2", name: DONAME.Busan },
      { id: "category_region_3", name: DONAME.Daegu },
      { id: "category_region_4", name: DONAME.Incheon },
      { id: "category_region_5", name: DONAME.Gwangju },
      { id: "category_region_6", name: DONAME.Daejeon },
      { id: "category_region_7", name: DONAME.Ulsan },
      { id: "category_region_8", name: DONAME.Sejong },
      { id: "category_region_9", name: DONAME.Gyeonggi },
      { id: "category_region_10", name: DONAME.Gangwon },
      { id: "category_region_11", name: DONAME.Chungcheongbuk },
      { id: "category_region_12", name: DONAME.Chungcheongnam },
      { id: "category_region_13", name: DONAME.Jeollabuk },
      { id: "category_region_14", name: DONAME.Jeollanam },
      { id: "category_region_15", name: DONAME.Gyeongsangbuk },
      { id: "category_region_16", name: DONAME.Gyeongsangnam },
      { id: "category_region_17", name: DONAME.Jeju },
    ],
    name: "region",
    className: "",
    warningMsg: "",
  },
  operation: {
    content: [
      { id: "category_opstype1", name: "지자체" },
      { id: "category_opstype2", name: "국립공원" },
      { id: "category_opstype3", name: "자연휴양림" },
      { id: "category_opstype4", name: "국민여가" },
      { id: "category_opstype5", name: "민간" },
    ],
    id: "category_opstype",
    title: "운영형태",
    name: "opstype",
    className: "",
    warningMsg: "",
  },
  location: {
    content: [
      { id: "category_locationtype1", name: "해변" },
      { id: "category_locationtype2", name: "섬" },
      { id: "category_locationtype3", name: "산" },
      { id: "category_locationtype4", name: "숲" },
      { id: "category_locationtype5", name: "계곡" },
      { id: "category_locationtype6", name: "호수" },
      { id: "category_locationtype7", name: "도심" },
    ],
    id: "category_locationtype",
    title: "입지구분",
    name: "locationtype",
    className: "",
    warningMsg: "",
  },
  campsite: {
    content: [
      { id: "category_campingsitetype1", name: "일반야영장" },
      { id: "category_campingsitetype2", name: "자동차야영장" },
      { id: "category_campingsitetype3", name: "카라반" },
      { id: "category_campingsitetype4", name: "글램핑" },
    ],
    id: "category_campingsitetype",
    title: "주요시설",
    name: "campingsitetype",
    className: "",
    warningMsg: "",
  },
  floor: {
    content: [
      { id: "category_floortype1", name: "잔디" },
      { id: "category_floortype2", name: "데크" },
      { id: "category_floortype3", name: "파쇄석" },
      { id: "category_floortype4", name: "자갈" },
      { id: "category_floortype5", name: "맨흙" },
    ],
    id: "category_floortype",
    title: "바닥형태",
    name: "floortype",
    className: "",
    warningMsg: "",
  },
  theme: {
    content: [
      { id: "category_theme1", name: "일출명소" },
      { id: "category_theme2", name: "일몰명소" },
      { id: "category_theme3", name: "수상레저" },
      { id: "category_theme4", name: "항공레저" },
      { id: "category_theme5", name: "스키" },
      { id: "category_theme6", name: "낚시" },
      { id: "category_theme7", name: "액티비티" },
      { id: "category_theme8", name: "봄꽃여행" },
      { id: "category_theme9", name: "여름물놀이" },
      { id: "category_theme10", name: "가을단풍명소" },
      { id: "category_theme11", name: "겨울눈꽃명소" },
      { id: "category_theme12", name: "걷기길" },
    ],
    id: "category_theme",
    title: "테마별",
    name: "theme",
    className: "",
    warningMsg: "",
  },
  facility: {
    content: [
      { id: "category_facility1", name: "전기" },
      { id: "category_facility2", name: "무선인터넷" },
      { id: "category_facility3", name: "장작판매" },
      { id: "category_facility4", name: "온수" },
      { id: "category_facility5", name: "트렘폴린" },
      { id: "category_facility6", name: "물놀이장" },
      { id: "category_facility7", name: "놀이터" },
      { id: "category_facility8", name: "산책로" },
      { id: "category_facility9", name: "운동장" },
      { id: "category_facility10", name: "운동시설" },
      { id: "category_facility11", name: "마트.편의점" },
    ],
    id: "category_facility",
    title: "부대시설",
    name: "facility",
    className: "",
    warningMsg: "",
  },
  etcinfo: {
    content: [
      { id: "category_etcinfo1", name: "개인 트레일러 입장가능" },
      { id: "category_etcinfo2", name: "개인 캠핑카 입장가능" },
      { id: "category_etcinfo3", name: "반려동물 동반가능" },
    ],
    id: "category_etcinfo",
    title: "기타정보",
    name: "etcinfo",
    className: "",
    warningMsg: "(※ 실제 결과는 현장사정 및 계절에 따라 달라질수 있으니 캠핑장 사업주에 직접 확인 후 이용바랍니다.)",
  },
};
