import { gql } from "@apollo/client";
import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { initializeApollo } from "../lib/apolloClient";
import { CampInfo } from "../types/campType";
import styles from "../styles/Home.module.css";

interface HomeInterface {
  data: { allCampPaged: CampInfo[] };
}

const Home: NextPage<HomeInterface> = ({ data }) => {
  const allCamps = data.allCampPaged;
  return (
    <div className={styles.container}>
      <Head>
        <title>gocamp | home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to gocamp landing test</h1>
        <ul>
          {allCamps.map((camps: CampInfo) => {
            return (
              <li key={`${camps.contentId}`}>
                <p>{`${camps.facltNm} : ${camps.addr1} ${camps.addr2 === null ? "" : camps.addr2}`}</p>
              </li>
            );
          })}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const apolloClient = initializeApollo();

  const { data } = await apolloClient.query({
    query: gql`
      query AllCampPaged($page: Int, $size: Int) {
        allCampPaged(page: $page, size: $size) {
          contentId
          facltNm
          addr1
          addr2
        }
      }
    `,
    variables: { page: 0, size: 10 },
  });
  return {
    props: {
      data,
    },
  };
};
